baseURL = 'https://noalemadic.netlify.app'
languageCode = 'en-us'
title = 'noalemadic'
theme = "PaperMod"

[params]
  [params.profileMode]
    enabled = true
    title = "Hi! Ich bin Noah."
    subtitle = "Auf dieser Seite findest du Berichte über meine Reisen und Erlebnisse. Aktuell bin ich in der Toskana mit dem Fahrrad unterwegs."
    imageUrl = "https://images.unsplash.com/photo-1599850929872-2dec3cbafd7f"  # Ersetze mit deinem Bild
    imageTitle = "Profilbild von Noah"
    imageWidth = 150  # Optional, Bildgröße anpassen
    imageHeight = 150  # Optional, Bildgröße anpassen

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://www.instagram.com/n0.h29/"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/yourusername"

