baseURL = 'https://noalemadic.netlify.app'
languageCode = 'en-us'
title = 'noalemadic'
theme = "PaperMod"

[params]
  [params.homeInfoParams]
    title = "Hi, ich bin Noah."
    content = "Auf dieser Seite findest du Berichte über meine Reisen und Erlebnisse. Aktuell bin ich in der Toskana mit dem Fahrrad unterwegs."
    subtitle: "This is subtitle"
    imageUrl: "https://images.unsplash.com/photo-1599850929872-2dec3cbafd7f?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    imageTitle: "Unsplash Platzhalter Image"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://www.instagram.com/n0.h29/"
  
  [[params.socialIcons]]
    name = "<platform 2>"
    url = "<link2>"
