params:
  homeInfoParams:
    Title: Hi! Ich bin Noah.
    Content: Auf dieser Seite findest du Berichte über meine Reisen und Erlebnisse. Aktuell bin ich in der Toskana mit dem Fahrrad unterwegs. 

  socialIcons: # optional
    - name: "Instagram"
      url: "https://www.instagram.com/n0.h29/"
    - name: "<platform 2>"
      url: "<link2>"