baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'noalemadic'
theme = "PaperMod"

[params]
  defaultTheme = "auto"  # Can be "auto", "light", or "dark"
  ShowReadingTime = true  # Show reading time on posts
  ShowShareButtons = true # Show social share buttons
  ShowBreadCrumbs = true  # Enable breadcrumbs navigation
  ShowPostNavLinks = true # Show previous/next post links
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

    socialIcons: # optional
    - name: "<platform>"
        url: "<link>"
    - name: "<platform 2>"
        url: "<link2>"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"

