baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'Netlify + Hugo Quickstart'
theme = "PaperMod"

params:
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"