# Netlify build settings for Hugo
[build]
  command = "hugo --minify"  # Ensures optimized production build
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.7"  # Updated to required version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
