backend:
  name: git-gateway
  branch: main  # Falls dein Hauptbranch anders heißt (z. B. "master"), anpassen

media_folder: "static/images/uploads"  # Speicherort für hochgeladene Bilder
public_folder: "/images/uploads"  # URL-Pfad für die Bilder

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }