backend:
  name: git-gateway
  branch: main  # Falls dein Hauptbranch anders heißt, z. B. "master", ändere es hier

media_folder: "static/images/uploads"  # Wo hochgeladene Bilder gespeichert werden
public_folder: "/images/uploads"  # Pfad, der in den Artikeln verwendet wird

collections:
  - name: "blog"  # Name der Sammlung
    label: "Blog"  # Wird in Netlify CMS angezeigt
    folder: "content/posts"  # Wo die Blog-Artikel gespeichert werden
    create: true  # Erlaube das Erstellen neuer Posts
    slug: "{{slug}}"  # Automatische URL-Bildung aus dem Titel
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
